version: '3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./backend:/usr/src/app
      # - type: bind
      #   source: $GIT_PRIVATE_KEY
      #   target: "/root/.ssh/id_rsa"
    working_dir: /usr/src/app
    command: /bin/bash
    tty: true
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ./frontend:/usr/src/app
      # - type: bind
      #   source: $GIT_PRIVATE_KEY
      #   target: "/root/.ssh/id_rsa"
    environment:
      - DEBUG=0
    ports:
      - "$MACHINE_PORT:3000"
    working_dir: /usr/src/app
    command: /bin/bash
    tty: true
    networks:
      - internal

networks:
  internal:
    driver: bridge