version: '3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - type: bind
        source: $GIT_PRIVATE_KEY
        target: "/root/.ssh/id_rsa"
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - type: bind
        source: $GIT_PRIVATE_KEY
        target: "/root/.ssh/id_rsa"
    tty: true